// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEliJnrITg1NIN7EWKJne0LsEkFAVlGCk',
    appId: '1:36674303374:web:6ff37a0d53675125be60df',
    messagingSenderId: '36674303374',
    projectId: 'carrier-hive',
    authDomain: 'carrier-hive.firebaseapp.com',
    storageBucket: 'carrier-hive.firebasestorage.app',
    measurementId: 'G-677SJHBK8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37Mh9bxw9oA0VUsWeImLeRCPd-21w7no',
    appId: '1:36674303374:android:5157f4b4a0b8a82bbe60df',
    messagingSenderId: '36674303374',
    projectId: 'carrier-hive',
    storageBucket: 'carrier-hive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBekCjb5Y69sVFqBu7OEnVinH7FgaD4bBI',
    appId: '1:36674303374:ios:d9bfa6521daf2bd4be60df',
    messagingSenderId: '36674303374',
    projectId: 'carrier-hive',
    storageBucket: 'carrier-hive.firebasestorage.app',
    iosBundleId: 'com.example.carrierHive',
  );
}
